### ISSUE TITLE
Service provider issue in Laravel 5.2

### ISSUE THREAD

**Issue by Sithira** [znck/flash#1]
This package wont work out of the box for laravel 5.2 since bindShared method is depreciated . So in order to work you should change the bindShared method to singleton method 

```
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('flash', function () {
            return $this->app->make('Znck\Flash\FlashNotifier');
        });

        $this->mergeConfigFrom(__DIR__ . '/../config/flash.php', 'znck.flash');
    }
```

**Comment by Sithira** [comment]
The fix is suggested above . just change the bindShared method to singleton method . it will work as expected :)

**Comment by znck** [comment]
@Sithira :+1:
